import type { Ticket, Conversation } from "./features/tickets/ticketSlice"
import type { User } from "./features/auth/authSlice"

export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@quickdesk.com",
    name: "Admin User",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=admin",
    department: "IT Support",
    isActive: true,
  },
  {
    id: "2",
    email: "agent@quickdesk.com",
    name: "Support Agent",
    role: "agent",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=agent",
    department: "IT Support",
    isActive: true,
  },
  {
    id: "3",
    email: "user@quickdesk.com",
    name: "End User",
    role: "user",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=user",
    department: "Marketing",
    isActive: true,
  },
  {
    id: "4",
    email: "john@quickdesk.com",
    name: "John Doe",
    role: "user",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=john",
    department: "Sales",
    isActive: true,
  },
  {
    id: "5",
    email: "sarah@quickdesk.com",
    name: "Sarah Wilson",
    role: "agent",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=sarah",
    department: "IT Support",
    isActive: true,
  },
]

const mockConversations: Conversation[] = [
  {
    id: "1",
    message: "I am unable to access my email account. It keeps showing authentication failed.",
    author: "3",
    authorName: "End User",
    authorRole: "user",
    timestamp: "2024-01-15T09:00:00Z",
  },
  {
    id: "2",
    message:
      "Thank you for contacting support. I will help you resolve this issue. Can you please try resetting your password?",
    author: "2",
    authorName: "Support Agent",
    authorRole: "agent",
    timestamp: "2024-01-15T09:15:00Z",
  },
  {
    id: "3",
    message: "I tried resetting the password but still getting the same error.",
    author: "3",
    authorName: "End User",
    authorRole: "user",
    timestamp: "2024-01-15T09:30:00Z",
  },
  {
    id: "4",
    message: "Let me check the server logs. This might be a server-side issue.",
    author: "2",
    authorName: "Support Agent",
    authorRole: "agent",
    timestamp: "2024-01-15T09:45:00Z",
    isInternal: true,
  },
]

export const mockTickets: Ticket[] = [
  {
    id: "1",
    subject: "Email Authentication Issue",
    description: "Unable to access email account, authentication keeps failing",
    status: "in-progress",
    priority: "high",
    category: "Email & Communication",
    createdBy: "3",
    assignedTo: "2",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T09:45:00Z",
    conversations: mockConversations,
    upvotes: ["4", "5"],
    downvotes: [],
    tags: ["email", "authentication", "urgent"],
  },
  {
    id: "2",
    subject: "Software Installation Request",
    description: "Need Adobe Creative Suite installed on my workstation",
    status: "open",
    priority: "medium",
    category: "Software & Applications",
    createdBy: "4",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T10:00:00Z",
    conversations: [
      {
        id: "5",
        message: "I need Adobe Creative Suite installed on my workstation for the upcoming project.",
        author: "4",
        authorName: "John Doe",
        authorRole: "user",
        timestamp: "2024-01-15T10:00:00Z",
      },
    ],
    upvotes: ["3"],
    downvotes: [],
    tags: ["software", "installation"],
  },
  {
    id: "3",
    subject: "Network Connectivity Problem",
    description: "Intermittent network disconnections in conference room B",
    status: "resolved",
    priority: "low",
    category: "Network & Infrastructure",
    createdBy: "3",
    assignedTo: "5",
    createdAt: "2024-01-14T14:00:00Z",
    updatedAt: "2024-01-15T08:00:00Z",
    conversations: [
      {
        id: "6",
        message: "The network in conference room B keeps disconnecting during meetings.",
        author: "3",
        authorName: "End User",
        authorRole: "user",
        timestamp: "2024-01-14T14:00:00Z",
      },
      {
        id: "7",
        message:
          "I have checked the network equipment and replaced the faulty cable. The issue should be resolved now.",
        author: "5",
        authorName: "Sarah Wilson",
        authorRole: "agent",
        timestamp: "2024-01-15T08:00:00Z",
      },
    ],
    upvotes: ["2", "4"],
    downvotes: [],
    tags: ["network", "infrastructure"],
  },
  {
    id: "4",
    subject: "Printer Not Working",
    description: "Office printer on 2nd floor is not responding",
    status: "open",
    priority: "urgent",
    category: "Hardware & Equipment",
    createdBy: "4",
    createdAt: "2024-01-15T11:00:00Z",
    updatedAt: "2024-01-15T11:00:00Z",
    conversations: [
      {
        id: "8",
        message: "The printer on the 2nd floor is completely unresponsive. We have an important presentation to print.",
        author: "4",
        authorName: "John Doe",
        authorRole: "user",
        timestamp: "2024-01-15T11:00:00Z",
      },
    ],
    upvotes: ["3", "5"],
    downvotes: ["2"],
    tags: ["printer", "hardware", "urgent"],
  },
  {
    id: "5",
    subject: "VPN Connection Issues",
    description: "Cannot connect to company VPN from home",
    status: "open",
    priority: "high",
    category: "Network & Infrastructure",
    createdBy: "3",
    createdAt: "2024-01-15T12:00:00Z",
    updatedAt: "2024-01-15T12:00:00Z",
    conversations: [
      {
        id: "9",
        message: "I'm unable to connect to the company VPN from my home office. Getting connection timeout errors.",
        author: "3",
        authorName: "End User",
        authorRole: "user",
        timestamp: "2024-01-15T12:00:00Z",
      },
    ],
    upvotes: ["4"],
    downvotes: [],
    tags: ["vpn", "remote-work"],
  },
]
